### PR TITLE
Update runtime to KDE 5.15

### PR DESCRIPTION
**Pull request by hfiguiere**
Also disable Wayland. Among the bug, changing the output DPI to a custom value wasn't possible.

### CODE REVIEW

**Comment by hfiguiere** [comment]
This extra patch fixes the JPEG compression support caused by the Freedesktop SDK:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1117

**Comment by Unrud** [comment]
> Also disable Wayland. Among the bug, changing the output DPI to a custom value wasn't possible.

Setting a custom output DPI value works fine for me with the wayland backend (tested on Fedora Silverblue 33).

**Comment by hfiguiere** [comment]
with runtime 5.15? 

It seems that Qt 5.15 introduce a lot of wayland regressions. The beta branch with the EA version is even worse.

**Comment by Unrud** [comment]
> with runtime 5.15?

Yes, I've tried both 5.14 and 5.15.

**Comment by Unrud** [comment]
> It seems that Qt 5.15 introduce a lot of wayland regressions. The beta branch with the EA version is even worse.

I've cherry-picked the libtiff commit for the master and beta branch. I guess it's best to keep the old QT version for now.

**Comment by hfiguiere** [comment]
I tried again with the version on flathub, with KDE 5.14 runtime.

The bug is there. If I run with --nosocket=wayland the bug is gone. So it's not a 5.14-5.15 bug.

To reproduce: 
- open a project.
- Go to the output phase
- Output Resolution -> Change
- In the dialog DPI -> Custom and try to enter a DPI number.

With the bug, you can't enter any number.

Disabling Wayland, I can.

BTW the dialog above doesn't appear in the same place between X11 and Wayland.

The host is Fedora 33 + GNOME 3 (stock Fedora) with an Intel HD Graphics 620.

For the record I have seen other issues with Qt apps that disappear when using X11.

**Comment by Unrud** [comment]
> With the bug, you can't enter any number.

Entering numbers works fine for me on Wayland.

> BTW the dialog above doesn't appear in the same place between X11 and Wayland.

Yes, dialogs are all over the place on wayland. Modal dialogs appear outside of the main window, when it's not maximized.

**Comment by hfiguiere** [comment]
Well, there is a bug somewhere and the solution is to disable Wayland.

**Comment by hfiguiere** [comment]
rebased my branch

**Comment by hfiguiere** [comment]
About the issue with wayland. Qt5 upstream disable wayland QPA if running in GNOME (I do). But it seems the SDK reenable it.

Source:
https://invent.kde.org/packaging/flatpak-kde-runtime/-/commit/d2db53cd10241dee6b11a5ad097e3e61a978a14e

So if you don't run GNOME that probably explain why you don't see the problems.

**Comment by Unrud** [comment]
> So if you don't run GNOME that probably explain why you don't see the problems.

I'm using GNOME.

**Comment by Unrud** [comment]
Merged without disabling Wayland: cf2a55c040ae980cbe4ffc900dc27dcce80c9714 + ae714b29ed31833ecb827b7825326128a8af3016

Maybe it would be better to configure Qt to prefer X11 over Wayland instead of disabling Wayland.

**Comment by hfiguiere** [comment]
> Maybe it would be better to configure Qt to prefer X11 over Wayland instead of disabling Wayland.

If you prefer it, but I believe `QT_QPA_PLATFORM=xcb` is equivalent to not have the wayland socket.

**Comment by Unrud** [comment]
> I believe `QT_QPA_PLATFORM=xcb` is equivalent to not have the wayland socket.

It also accepts a list of plugins separated by `;`. They are tried in order.

**Comment by hfiguiere** [comment]
closing this, it's obsolete.

**Pull request closed without merging**
